### ISSUE TITLE
Plans to make this an embeddable library?

### ISSUE THREAD

**Issue by tylerdigital** [afragen/translations-updater#2]
This looks great and solves a real issue with translations. The one hurdle I see, is requiring users to install another plugin. Are there any plans to make this an embeddable library/class/file that I could embed as a plugin author?

**Comment by afragen** [comment]
I haven’t thought about it but I’m sure I could. 

It would need to be installed via composer. 

I can take a look at doing this. Perhaps another branch here to start. 

Have you looked at the Language Pack Maker framework? It’s the requirement for the repository of translations.

**Comment by afragen** [comment]
If added as an embeddable library should we require an array sent as config within your project? 

This could simplify the code required, but also make the implementation take a bit more time.

**Comment by afragen** [comment]
It might be easier to use https://github.com/afragen/edd-translations-updater as a starting point as it already uses an array passed via a filter hook.

**Comment by afragen** [comment]
@tylerdigital I've made some progress in the conversion. https://github.com/afragen/translations-updater/tree/composer

I still haven't added the ability to install via composer as I would need to either change the repo name (got any ideas) or overwrite the plugin (which I'm leaning towards).

It's currently a plugin but for my testing only at the moment. I also have my own Autoloader which would go away with composer.

Thoughts?

**Comment by afragen** [comment]
Testing time. The `composer` branch should be functional.

`composer require afragen/translations-updater:dev-composer` for testing.

More info in the README. Ask questions here.

**Comment by afragen** [comment]
I think this is now feature complete and really needs another set of eyes to let me know if there are any issues.

 https://github.com/afragen/translations-updater/tree/composer

**Comment by afragen** [comment]
Now merged into the develop branch.

**Comment by afragen** [comment]
And in master.
